Changed insert to optionally insert into latest table (default true)
trueaccord/repos pull request #3
Opened 2017-04-10 17:45 UTC by zkwong1

This is to satisfy a situation where the latest can be inserted later and to break a transactional lock that does not appear to make sense.

2017-04-10 17:50 UTC, nandrienko commented
Please add unit tests

2017-04-10 17:53 UTC, nandrienko requested changes
Please add unit tests too

2017-04-10 17:53 UTC, nandrienko commented on src/main/scala/repos/jdbc/JdbcDb.scala
> +          pkList <- entryTable.returning(entryTable.map(_.pk)) ++= newEntries
Can it be factored out in a separate function such that in case of insertLatest it is just composed with DBIO.sequence(...) block?

2017-04-10 19:09 UTC, zkwong1 commented on src/main/scala/repos/jdbc/JdbcDb.scala
> +          pkList <- entryTable.returning(entryTable.map(_.pk)) ++= newEntries
I tried, but it resulted in errors. In the case where a latest insert should happen, the pkList should only be yielded if the sequence can be generated and then run transactionally correct?

2017-04-10 19:27 UTC, zkwong1 commented
Added unit tests, but it is difficult to test due to

2017-04-11 21:16 UTC, nandrienko commented on src/main/scala/repos/jdbc/JdbcDb.scala
> +import slick.dbio.Effect.{Read, Write}
is Write really required now?

2017-04-11 21:16 UTC, nandrienko commented on src/main/scala/repos/jdbc/JdbcDb.scala
> +      val newEntries: Iterable[EntryTableRecord[Id, M]] = elements.map(e => EntryTableRecord[Id, M](-1, e._1, System.currentTimeMillis(), e._2))
Remove type annotation or make muiltiline

2017-04-11 21:16 UTC, nandrienko commented on src/main/scala/repos/jdbc/JdbcDb.scala
> +    def insert(elements: Iterable[(Id, M)], skipIndexesForTesting: Boolean = false, insertLatest: Boolean = true)(implicit ec: ExecutionContext): Future[Seq[Long]] = {
insertIntoLatest?

2017-04-11 21:16 UTC, nandrienko commented on src/main/scala/repos/inmem/InMemRepoImpl.scala
> +    val prepared: Seq[(Id, (Long, M))] = entries.map(e => e.id ->(e.pk, e.entry))
?

2017-04-11 21:16 UTC, nandrienko commented on src/main/scala/repos/inmem/InMemDb.scala
> +      case InsertAction(repo, entries, insertLatest) if insertLatest =>
insertIntoLatest

2017-04-11 21:16 UTC, nandrienko commented on src/main/scala/repos/Action.scala
> +  case class InsertAction[Id, M](repo: Repo[Id, M], entries: Seq[(Id, M)], insertLatest: Boolean = true) extends RepoAction[NoStream, Id, M, Unit]
insertIntoLatest

2017-04-11 21:17 UTC, zkwong1 commented on src/main/scala/repos/jdbc/JdbcDb.scala
> +import slick.dbio.Effect.{Read, Write}
No longer required.

2017-04-11 21:22 UTC, zkwong1 commented on src/main/scala/repos/inmem/InMemRepoImpl.scala
> +    val prepared: Seq[(Id, (Long, M))] = entries.map(e => e.id ->(e.pk, e.entry))
This is to separate out the InMemRepoImpl's insert to reuse the insertWithoutLatest function. The order won't be exactly the same as before.

2017-04-12 00:55 UTC, nandrienko approved these changes

2017-04-12 00:57 UTC, merged